#pragma once

#include <array>

static const std::array<const char *, 47 > discardable_tags = { {
	"created_by",
	"converted_by",
	"odbl",
	"odbl:note",
	"tiger:upload_uuid",
	"tiger:tlid",
	"tiger:source",
	"tiger:separated",
	"geobase:datasetName",
	"geobase:uuid",
	"osmarender:nameDirection",
	"osmarender:renderName",
	"osmarender:renderRef",
	"osmarender:rendernames",
	"sub_sea:type",
	"KSJ2:ADS",
	"KSJ2:ARE",
	"KSJ2:AdminArea",
	"KSJ2:COP_label",
	"KSJ2:DFD",
	"KSJ2:INT",
	"KSJ2:INT_label",
	"KSJ2:LOC",
	"KSJ2:LPN",
	"KSJ2:OPC",
	"KSJ2:PubFacAdmin",
	"KSJ2:RAC",
	"KSJ2:RAC_label",
	"KSJ2:RIC",
	"KSJ2:RIN",
	"KSJ2:WSC",
	"KSJ2:coordinate",
	"KSJ2:curve_id",
	"KSJ2:curve_type",
	"KSJ2:filename",
	"KSJ2:lake_id",
	"KSJ2:lat",
	"KSJ2:long",
	"KSJ2:river_id",
	"SK53_bulk:load",
	"yh:LINE_NAME",
	"yh:LINE_NUM",
	"yh:STRUCTURE",
	"yh:TOTYUMONO",
	"yh:TYPE",
	"yh:WIDTH",
	"yh:WIDTH_RANK",
}};
